# Generated by Django 5.2.5 on 2025-08-26 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='manager',
            field=models.OneToOneField(limit_choices_to={'specialization': 'Manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_department', to='users.profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.department'),
        ),
    ]
